search_input_graph_path: /home/ehussein/ArabesqueWorkspace/ArabesqueQFrag/Arabesque/data/citeseer.graph
search_output_path: /home/ehussein/ArabesqueWorkspace/ArabesqueQFrag/Arabesque/data/output-search
search_output_active: true
system_type: search
search_injective: true
search_outliers_pct: 0.1
search_outliers_min_matches: 0
search_fastNeighbors: true
search_write_in_binary: false
search_query_graph_path: /home/ehussein/ArabesqueWorkspace/ArabesqueQFrag/Arabesque/data/queries/Q5u
search_num_vertices: 0
search_num_edges: 0
search_num_labels: 0
log_level: info
spark_master: local[*]
driver_memory: 8g
worker_memory: 10g
num_workers: 1
num_compute_threads: 6
