search_injective: true
search_outliers_pct: 0.0
search_outliers_min_matches: 0
search_fastNeighbors: true
search_write_in_binary: false
search_query_graph_path: ./data/queries/Q1-citeseer
search_output_path: output-search/gj-citeseer-1
search_input_graph_path: ./data/citeseer.unsafe.graph
search_output_active: false
search_num_vertices: 3312
search_num_edges: 9072
search_num_labels: 6
log_level: fatal
system_type: search
